/**
 * Manual header-image upload → thread facts Auto can see on later turns.
 *
 * upload-header-image writes the image onto the draft AND records a durable
 * system message on the active thread. chat.js folds unconsumed facts into
 * systemFacts so Auto knows the upload happened without Bart pasting a URL.
 */

export const MANUAL_HEADER_UPLOAD_KIND = 'manual_header_upload';

/**
 * Human + model-readable fact line.
 */
export function formatManualHeaderUploadFact({
  slug,
  imageUrl,
  title = null,
  timestamp = null,
}) {
  const when = timestamp || new Date().toISOString();
  const titleBit = title ? ` ("${title}")` : '';
  return (
    `[SYSTEM] User manually uploaded a header image directly to draft '${slug}'${titleBit} ` +
    `at ${when}. Image URL: ${imageUrl}. This was not generated by Auto.`
  );
}

/**
 * Persist a system fact on the thread after a successful direct-to-draft upload.
 */
export async function recordManualHeaderUploadFact({
  email,
  threadId = null,
  slug,
  imageUrl,
  title = null,
}) {
  const emailNorm = String(email || '')
    .toLowerCase()
    .trim();
  const safeSlug = String(slug || '').trim();
  const url = String(imageUrl || '').trim();
  if (!emailNorm) return { ok: false, error: 'email is required' };
  if (!safeSlug) return { ok: false, error: 'slug is required' };
  if (!url) return { ok: false, error: 'imageUrl is required' };

  try {
    const { addAutoMessage, ensureAutoThread } = await import('./autoHub.js');
    const thread = await ensureAutoThread(emailNorm, threadId || '');
    const timestamp = new Date().toISOString();
    const fact = formatManualHeaderUploadFact({
      slug: safeSlug,
      imageUrl: url,
      title,
      timestamp,
    });

    const message = await addAutoMessage({
      threadId: thread.id,
      role: 'system',
      mode: 'plan',
      content: fact,
      meta: {
        kind: MANUAL_HEADER_UPLOAD_KIND,
        slug: safeSlug,
        image_url: url,
        title: title || null,
        consumed: false,
        recorded_at: timestamp,
      },
    });

    return { ok: true, message, fact, thread_id: thread.id };
  } catch (err) {
    return { ok: false, error: err?.message || String(err) };
  }
}

/**
 * Load recent unconsumed manual-upload facts for a thread.
 */
export async function loadUnconsumedManualHeaderUploadFacts(threadId, { limit = 10 } = {}) {
  const tid = String(threadId || '').trim();
  if (!tid) return { facts: [], messageIds: [] };

  const { supabaseAdmin } = await import('../supabase-admin.js');
  const { data, error } = await supabaseAdmin
    .from('ao_auto_messages')
    .select('id, content, meta, created_at')
    .eq('thread_id', tid)
    .eq('role', 'system')
    .order('created_at', { ascending: false })
    .limit(Math.min(Math.max(Number(limit) || 10, 1), 40));

  if (error || !Array.isArray(data)) {
    if (error) {
      console.error('[manualHeaderUploadFact] load failed:', error.message);
    }
    return { facts: [], messageIds: [] };
  }

  const facts = [];
  const messageIds = [];
  for (const row of data) {
    const meta = row?.meta && typeof row.meta === 'object' ? row.meta : {};
    if (meta.kind !== MANUAL_HEADER_UPLOAD_KIND) continue;
    if (meta.consumed === true) continue;
    const text = String(row.content || '').trim();
    if (!text) continue;
    facts.push(text);
    messageIds.push(row.id);
  }

  facts.reverse();
  messageIds.reverse();
  return { facts, messageIds };
}

/**
 * Mark facts as consumed after they were folded into a chat turn's systemFacts.
 */
export async function markManualHeaderUploadFactsConsumed(messageIds) {
  const ids = (Array.isArray(messageIds) ? messageIds : []).filter(Boolean);
  if (!ids.length) return { ok: true, updated: 0 };

  const { supabaseAdmin } = await import('../supabase-admin.js');
  let updated = 0;
  for (const id of ids) {
    const { data: existing } = await supabaseAdmin
      .from('ao_auto_messages')
      .select('id, meta')
      .eq('id', id)
      .maybeSingle();
    if (!existing) continue;
    const meta = existing.meta && typeof existing.meta === 'object' ? { ...existing.meta } : {};
    meta.consumed = true;
    meta.consumed_at = new Date().toISOString();
    const { error } = await supabaseAdmin
      .from('ao_auto_messages')
      .update({ meta })
      .eq('id', id);
    if (!error) updated += 1;
  }
  return { ok: true, updated };
}
