-- ============================================
-- ALI Survey Snapshot Schema
-- Purpose: Immutable survey definitions generated by deterministic builder
-- Supports: Versioning, auditability, longitudinal comparability
-- ============================================

-- SURVEY SNAPSHOTS (Immutable Generated Surveys)
CREATE TABLE IF NOT EXISTS ali_survey_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Survey Identity
  survey_index TEXT NOT NULL, -- "S1", "S2", "S3", etc.
  instrument_version TEXT NOT NULL DEFAULT 'v1.0', -- e.g., "v1.0", "v1.1"
  
  -- Generation Metadata (Deterministic Seed)
  client_id UUID NOT NULL REFERENCES ali_companies(id) ON DELETE CASCADE,
  generation_seed TEXT NOT NULL, -- hash(client_id + survey_index + instrument_version)
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  generated_by TEXT DEFAULT 'system', -- Always "system" for deterministic builds
  
  -- Question List (Immutable Ordered Array)
  question_stable_ids TEXT[] NOT NULL, -- Ordered list of stable_ids
  question_order JSONB NOT NULL, -- Full question metadata at generation time
  
  -- Composition Validation
  anchor_count INTEGER NOT NULL CHECK (anchor_count = 3),
  pattern_question_count INTEGER NOT NULL CHECK (pattern_question_count = 7),
  total_question_count INTEGER NOT NULL CHECK (total_question_count = 10),
  negative_item_count INTEGER NOT NULL CHECK (negative_item_count >= 2 AND negative_item_count <= 4),
  
  -- Immutability Enforcement
  is_locked BOOLEAN DEFAULT true, -- Always true for generated surveys
  locked_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Audit Trail
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT survey_snapshot_unique UNIQUE (client_id, survey_index, instrument_version)
  -- Note: Immutability enforced via trigger (is_locked always true)
);

-- SURVEY DEPLOYMENTS (Links Snapshots to Companies/Divisions)
-- Updated to reference survey_snapshots instead of ali_surveys
ALTER TABLE IF EXISTS ali_survey_deployments 
  DROP CONSTRAINT IF EXISTS ali_survey_deployments_survey_id_fkey;

-- Add snapshot_id column if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'ali_survey_deployments' AND column_name = 'snapshot_id'
  ) THEN
    ALTER TABLE ali_survey_deployments 
    ADD COLUMN snapshot_id UUID REFERENCES ali_survey_snapshots(id) ON DELETE RESTRICT;
  END IF;
END $$;

-- Keep survey_id for backward compatibility (can be deprecated later)
-- snapshot_id is the new primary reference

-- Add survey_index to deployments
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'ali_survey_deployments' AND column_name = 'survey_index'
  ) THEN
    ALTER TABLE ali_survey_deployments 
    ADD COLUMN survey_index TEXT;
  END IF;
END $$;

-- Add available_at to deployments (when survey becomes available)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'ali_survey_deployments' AND column_name = 'available_at'
  ) THEN
    ALTER TABLE ali_survey_deployments 
    ADD COLUMN available_at TIMESTAMPTZ;
  END IF;
END $$;

-- Add sent_at to deployments (when survey was actually sent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'ali_survey_deployments' AND column_name = 'sent_at'
  ) THEN
    ALTER TABLE ali_survey_deployments 
    ADD COLUMN sent_at TIMESTAMPTZ;
  END IF;
END $$;

-- ============================================
-- Indexes for Performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_survey_snapshots_client ON ali_survey_snapshots(client_id);
CREATE INDEX IF NOT EXISTS idx_survey_snapshots_index ON ali_survey_snapshots(survey_index);
CREATE INDEX IF NOT EXISTS idx_survey_snapshots_instrument ON ali_survey_snapshots(instrument_version);
CREATE INDEX IF NOT EXISTS idx_survey_snapshots_seed ON ali_survey_snapshots(generation_seed);
CREATE INDEX IF NOT EXISTS idx_survey_snapshots_unique ON ali_survey_snapshots(client_id, survey_index, instrument_version);

CREATE INDEX IF NOT EXISTS idx_survey_deployments_snapshot ON ali_survey_deployments(snapshot_id);
CREATE INDEX IF NOT EXISTS idx_survey_deployments_index ON ali_survey_deployments(survey_index);

-- ============================================
-- Immutability Enforcement Functions
-- ============================================

-- Prevent any updates to locked survey snapshots
CREATE OR REPLACE FUNCTION prevent_survey_snapshot_updates()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.is_locked = true THEN
    RAISE EXCEPTION 'Survey snapshot is immutable. Cannot modify locked survey.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER prevent_survey_snapshot_updates_trigger
BEFORE UPDATE ON ali_survey_snapshots
FOR EACH ROW
EXECUTE FUNCTION prevent_survey_snapshot_updates();

-- ============================================
-- Helper Function: Get Survey Snapshot by Client and Index
-- ============================================
CREATE OR REPLACE FUNCTION get_survey_snapshot(
  p_client_id UUID,
  p_survey_index TEXT,
  p_instrument_version TEXT DEFAULT 'v1.0'
)
RETURNS ali_survey_snapshots AS $$
  SELECT * FROM ali_survey_snapshots
  WHERE client_id = p_client_id
    AND survey_index = p_survey_index
    AND instrument_version = p_instrument_version
  LIMIT 1;
$$ LANGUAGE sql STABLE;

-- ============================================
-- Row Level Security
-- ============================================
ALTER TABLE ali_survey_snapshots ENABLE ROW LEVEL SECURITY;

-- Policy: Read access for authenticated users
-- (RLS policies to be added with auth system)

-- ============================================
-- Migration Notes
-- ============================================

-- Existing ali_surveys table can remain for:
-- 1. Manual/override surveys (if needed)
-- 2. Legacy compatibility
-- 3. Template storage (if desired)

-- New system uses ali_survey_snapshots exclusively for:
-- 1. System-generated surveys
-- 2. Deterministic builds
-- 3. Immutable question lists

