-- Content reshare queue — tracks journal entries rotated for weekly social reshares.
-- Run in Supabase SQL editor before enabling the reshare cron.

CREATE TABLE IF NOT EXISTS ao_reshare_queue (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title text,
  last_reshared_at timestamptz,
  reshare_count integer DEFAULT 0 NOT NULL,
  paused boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS ao_reshare_queue_last_reshared_idx
  ON ao_reshare_queue (last_reshared_at ASC NULLS FIRST);

CREATE INDEX IF NOT EXISTS ao_reshare_queue_paused_idx
  ON ao_reshare_queue (paused);

INSERT INTO ao_reshare_queue (slug, title, last_reshared_at, reshare_count)
VALUES
  ('accountability-comes-first', 'Accountability Comes First', NULL, 0),
  ('accountability-is-a-design-problem', 'Accountability Is a Design Problem', NULL, 0),
  ('affinity-dressed-as-service', 'Affinity Dressed as Service', NULL, 0),
  ('after-the-smoke-clears', 'After the Smoke Clears', NULL, 0),
  ('ali-series-alignment-when-the-direction-actually-holds', 'ALI Series: Alignment', NULL, 0),
  ('ali-series-clarity-what-actually-lands', 'ALI Series: Clarity', NULL, 0),
  ('ali-series-communication-the-message-that-actually-arrives', 'ALI Series: Communication', NULL, 0),
  ('ali-series-consistency-the-leader-people-learn-to-predict', 'ALI Series: Consistency', NULL, 0),
  ('ali-series-drift-the-condition-that-moves-without-permission', 'ALI Series: Drift', NULL, 0),
  ('ali-series-introducing-the-archetype-leadership-index', 'ALI Series: Introduction', NULL, 0),
  ('ali-series-stability-the-environment-that-holds', 'ALI Series: Stability', NULL, 0),
  ('ali-series-the-7-conditions-why-this-series-exists', 'ALI Series: The 7 Conditions', NULL, 0),
  ('ali-series-trust-the-condition-that-cannot-be-declared', 'ALI Series: Trust', NULL, 0),
  ('build-it-on-purpose', 'Build It on Purpose', NULL, 0),
  ('clearing-the-path', 'Clearing the Path', NULL, 0),
  ('cult-of-confusion', 'Cult of Confusion', NULL, 0),
  ('golden-rule-leadership-strategy', 'Golden Rule Leadership Strategy', NULL, 0),
  ('how-leaders-lose-the-capacity-for-accountability', 'How Leaders Lose the Capacity for Accountability', NULL, 0),
  ('how-pressure-triggers-threat-in-unaccountable-leaders', 'How Pressure Triggers Threat in Unaccountable Leaders', NULL, 0),
  ('how-unaccountable-leadership-becomes-structural', 'How Unaccountable Leadership Becomes Structural', NULL, 0),
  ('illusion-of-control', 'The Illusion of Control', NULL, 0),
  ('ive-spent-some-time-purposely-not-writing', 'I Have Spent Some Time Purposely Not Writing', NULL, 0),
  ('leadership-bottlenecks-will-choke-the-life-out-of-a-business', 'Leadership Bottlenecks Will Choke the Life Out of a Business', NULL, 0),
  ('leadership-is-not-a-clenched-fist-but-a-guiding-hand-part-1', 'Leadership Is Not a Clenched Fist: Part 1', NULL, 0),
  ('leadership-is-not-a-clenched-fist-but-a-guiding-hand-part-2', 'Leadership Is Not a Clenched Fist: Part 2', NULL, 0),
  ('leadership-is-not-a-clenched-fist-but-a-guiding-hand-part-3', 'Leadership Is Not a Clenched Fist: Part 3', NULL, 0),
  ('leadership-isnt-a-scoreboard', 'Leadership Is Not a Scoreboard', NULL, 0),
  ('leadership-shoes-and-melted-feet', 'Leadership Shoes and Melted Feet', NULL, 0),
  ('leading-well-under-bad-leadership', 'Leading Well Under Bad Leadership', NULL, 0),
  ('lone-wolves-die-young', 'Lone Wolves Die Young', NULL, 0),
  ('manufactured-crisis', 'Manufactured Crisis', NULL, 0),
  ('mean-people-suck', 'Mean People Suck', NULL, 0),
  ('most-people-hear-few-actually-listen', 'Most People Hear. Few Actually Listen.', NULL, 0),
  ('performance-of-perfection', 'The Performance of Perfection', NULL, 0),
  ('power-vs-authority-part-1-the-hunger', 'Power vs. Authority: Part 1', NULL, 0),
  ('power-vs-authority-part-2-the-build', 'Power vs. Authority: Part 2', NULL, 0),
  ('power-vs-authority-part-3-the-test', 'Power vs. Authority: Part 3', NULL, 0),
  ('psychology-of-servant-leadership-01', 'Psychology of Servant Leadership: 01', NULL, 0),
  ('psychology-of-servant-leadership-02', 'Psychology of Servant Leadership: 02', NULL, 0),
  ('psychology-of-servant-leadership-03', 'Psychology of Servant Leadership: 03', NULL, 0),
  ('psychology-of-servant-leadership-04', 'Psychology of Servant Leadership: 04', NULL, 0),
  ('psychology-of-servant-leadership-05', 'Psychology of Servant Leadership: 05', NULL, 0),
  ('psychology-of-servant-leadership-06', 'Psychology of Servant Leadership: 06', NULL, 0),
  ('recognizing-unsafe-leadership-environments', 'Recognizing Unsafe Leadership Environments', NULL, 0),
  ('shadow-of-shame', 'Shadow of Shame', NULL, 0),
  ('stop-turning-your-team-into-opponents', 'Stop Turning Your Team Into Opponents', NULL, 0),
  ('teams-are-not-wells', 'Teams Are Not Wells', NULL, 0),
  ('the-approval-economy', 'The Approval Economy', NULL, 0),
  ('the-case-for-servant-leadership-part-1', 'The Case for Servant Leadership: Part 1', NULL, 0),
  ('the-case-for-servant-leadership-part-2', 'The Case for Servant Leadership: Part 2', NULL, 0),
  ('the-case-for-servant-leadership-part-3', 'The Case for Servant Leadership: Part 3', NULL, 0),
  ('the-case-for-servant-leadership-part-4', 'The Case for Servant Leadership: Part 4', NULL, 0),
  ('the-case-for-servant-leadership-part-5', 'The Case for Servant Leadership: Part 5', NULL, 0),
  ('the-cost-of-calm', 'The Cost of Calm', NULL, 0),
  ('the-distraction-play', 'The Distraction Play', NULL, 0),
  ('the-invisible-tax', 'The Invisible Tax', NULL, 0),
  ('the-isolation-strategy', 'The Isolation Strategy', NULL, 0),
  ('the-judas-archetype', 'The Judas Archetype', NULL, 0),
  ('the-loyalty-economy', 'The Loyalty Economy', NULL, 0),
  ('the-pendulum-of-leadership-efficiency-vs-empathy', 'The Pendulum of Leadership', NULL, 0),
  ('the-producer-leader-paradox', 'The Producer-Leader Paradox', NULL, 0),
  ('the-proxy-trap', 'The Proxy Trap', NULL, 0),
  ('the-pursuit-of-power-corrupts', 'The Pursuit of Power Corrupts', NULL, 0),
  ('the-scarcity-switch', 'The Scarcity Switch', NULL, 0),
  ('the-work-is-now-public', 'The Work Is Now Public', NULL, 0),
  ('toxic-empathy', 'Toxic Empathy', NULL, 0),
  ('toxic-empathy-2-holding-the-line', 'Toxic Empathy: Holding the Line', NULL, 0),
  ('toxic-empathy-3-the-cost-of-avoidance', 'Toxic Empathy: The Cost of Avoidance', NULL, 0),
  ('toxic-empathy-4-servant-leadership-role', 'Toxic Empathy: Servant Leadership Role', NULL, 0),
  ('toxic-empathy-5-the-conversation', 'Toxic Empathy: The Conversation', NULL, 0),
  ('we-live-in-a-not-my-fault-era', 'We Live in a Not My Fault Era', NULL, 0),
  ('weve-lost-the-plot-on-leadership', 'We Have Lost the Plot on Leadership', NULL, 0),
  ('what-are-your-values-as-a-business-leader', 'What Are Your Values as a Business Leader', NULL, 0),
  ('when-leaders-refuse-to-change-the-enron-lesson', 'When Leaders Refuse to Change', NULL, 0),
  ('when-leadership-sank-kodak', 'When Leadership Sank Kodak', NULL, 0),
  ('when-responsibility-stops-being-accidental', 'When Responsibility Stops Being Accidental', NULL, 0),
  ('when-stability-replaces-accountability', 'When Stability Replaces Accountability', NULL, 0),
  ('where-we-begin', 'Where We Begin', NULL, 0),
  ('why-i-chose-the-name-archetype-original', 'Why I Chose the Name Archetype Original', NULL, 0),
  ('why-leaders-hire-me', 'Why Leaders Hire Me', NULL, 0),
  ('why-servant-leadership-disrupts-unaccountable-power', 'Why Servant Leadership Disrupts Unaccountable Power', NULL, 0),
  ('words-into-action', 'Words Into Action', NULL, 0),
  ('you-dont-win-alone-ever', 'You Do Not Win Alone. Ever.', NULL, 0)
ON CONFLICT (slug) DO NOTHING;
