import React from 'react';

export default function SpeakingWorkshops() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 pt-20">
      <div className="max-w-4xl mx-auto px-4">
        {/* Back button */}
        <div className="mb-8">
          <a 
            href="/" 
            className="inline-flex items-center text-gray-600 hover:text-gray-900 transition-colors"
          >
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Home
          </a>
        </div>

        {/* Page content */}
        <article className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          <div className="p-8">
            <h1 className="text-4xl font-bold text-gray-900 mb-6">Speaking & Workshops</h1>
            
            {/* PLACEHOLDER CONTENT - Replace with ChatGPT generated content */}
            <div className="prose prose-lg max-w-none">
              <p className="text-xl text-gray-700 mb-8">
                <strong>Content to be generated by ChatGPT:</strong> Keynotes and class lectures on business and leadership, business and group workshops on leadership, servant leadership, culture, team building, software and app development, marketing, etc. Basically, if it's business, I've had some level of exposure and experience.
              </p>
              
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 mb-8">
                <h3 className="text-lg font-semibold text-yellow-800 mb-2">Content Areas for ChatGPT:</h3>
                <ul className="list-disc list-inside text-yellow-700 space-y-1">
                  <li>Keynotes and class lectures on business and leadership</li>
                  <li>Business and group workshops</li>
                  <li>Topics: Leadership, servant leadership, culture, team building</li>
                  <li>Software and app development, marketing</li>
                  <li>Speaking experience and credentials</li>
                  <li>Workshop formats and customization</li>
                  <li>How to book / contact information</li>
                </ul>
              </div>
            </div>
          </div>
        </article>
      </div>
    </div>
  );
}
