import React from 'react';

export default function SpeakingWorkshops() {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="bg-white py-16 sm:py-20 md:py-24 lg:py-20">
        <div className="container mx-auto px-4 sm:px-6 md:px-12">
          <div className="max-w-5xl mx-auto text-center space-y-8">
            <h1 className="font-serif text-5xl sm:text-6xl md:text-7xl font-bold leading-[0.9] tracking-tight text-[#1A1A1A]">
              Speaking & Workshops
            </h1>
          </div>
        </div>
      </section>

      {/* Content Section */}
      <section className="bg-[#FAFAF9] py-16 sm:py-24 md:py-32">
        <div className="container mx-auto px-4 sm:px-6 md:px-12">
          <div className="max-w-4xl mx-auto">
            {/* Back button */}
            <div className="mb-8">
              <a 
                href="/" 
                className="inline-flex items-center text-[#1A1A1A]/70 hover:text-[#1A1A1A] transition-colors"
              >
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Back to Home
              </a>
            </div>

            {/* Page content */}
            <article className="bg-white rounded-lg shadow-sm border border-[#1A1A1A]/10 overflow-hidden">
              <div className="p-8">
            
            {/* PLACEHOLDER CONTENT - Replace with ChatGPT generated content */}
            <div className="prose prose-lg max-w-none">
              <p className="text-xl text-gray-700 mb-8">
                <strong>Content to be generated by ChatGPT:</strong> Keynotes and class lectures on business and leadership, business and group workshops on leadership, servant leadership, culture, team building, software and app development, marketing, etc. Basically, if it's business, I've had some level of exposure and experience.
              </p>
              
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 mb-8">
                <h3 className="text-lg font-semibold text-yellow-800 mb-2">Content Areas for ChatGPT:</h3>
                <ul className="list-disc list-inside text-yellow-700 space-y-1">
                  <li>Keynotes and class lectures on business and leadership</li>
                  <li>Business and group workshops</li>
                  <li>Topics: Leadership, servant leadership, culture, team building</li>
                  <li>Software and app development, marketing</li>
                  <li>Speaking experience and credentials</li>
                  <li>Workshop formats and customization</li>
                  <li>How to book / contact information</li>
                </ul>
              </div>
            </div>
          </div>
        </article>
          </div>
        </div>
      </section>
    </div>
  );
}
