import React, { useCallback, useMemo, useState } from 'react';

const IS_LINES = [
  'A live, in-person gathering for active leaders',
  'A structured room with real accountability',
  'A conversation generated by the people attending it',
  'A community earned through participation, not paid for',
  'A place where the real cost is posture, not money',
];

const ISNT_LINES = [
  'A networking event or leads group',
  'A seminar, workshop, or keynote experience',
  'A mastermind with a curriculum',
  'A place to pitch your business',
  'Open to everyone who applies',
];

const COMPANY_OPTIONS = [
  { value: '', label: 'Select range', disabled: true },
  { value: '1-4', label: '1–4 employees' },
  { value: '5-25', label: '5–25 employees' },
  { value: '26-100', label: '26–100 employees' },
  { value: '101-250', label: '101–250 employees' },
  { value: '250+', label: '250+ employees' },
];

export default function OperatorsLanding() {
  const handleNavigate = useCallback((path) => {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
    window.scrollTo({ top: 0, behavior: 'instant' });
  }, []);

  const scrollToApply = useCallback((e) => {
    if (e?.preventDefault) e.preventDefault();
    document.getElementById('apply')?.scrollIntoView({ behavior: 'smooth' });
  }, []);

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [roleTitle, setRoleTitle] = useState('');
  const [companySize, setCompanySize] = useState('');
  const [bio, setBio] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [success, setSuccess] = useState(false);

  const bioLen = bio.length;
  const counterText = useMemo(() => {
    const base = `${bioLen} characters`;
    if (bioLen < 100) return `${base} (${100 - bioLen} more needed)`;
    return base;
  }, [bioLen]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMessage('');
    if (bio.trim().length < 100) {
      setErrorMessage('Your bio needs to be at least 100 characters.');
      return;
    }
    if (!companySize) {
      setErrorMessage('Please select your company size.');
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/operators/interest/submit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: name.trim(),
          email: email.trim(),
          role_title: roleTitle.trim(),
          company_size: companySize,
          bio: bio.trim(),
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok || !data.ok) {
        setErrorMessage(data.error || 'Something went wrong. Please try again.');
        setSubmitting(false);
        return;
      }
      setSuccess(true);
    } catch {
      setErrorMessage('Something went wrong. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const sectionInner = 'mx-auto max-w-[1400px] px-6 sm:px-10';

  return (
    <div className="min-h-screen bg-[var(--color-off-white)] font-inter text-[15px] leading-relaxed text-[#1A1A1A] antialiased">
      {/* NAV */}
      <nav className="absolute left-0 right-0 top-0 z-50 border-b border-white/10 bg-transparent">
        <div className={sectionInner}>
          <div className="flex h-16 items-center justify-between">
            <button
              type="button"
              onClick={() => handleNavigate('/operators')}
              className="font-playfair text-[20px] font-normal tracking-wide text-white"
            >
              The Operators
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/operators/login')}
              className="text-[12px] font-semibold uppercase tracking-[0.08em] text-white/60 transition-colors hover:text-white"
            >
              Log In
            </button>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="relative flex min-h-[88vh] w-full items-end overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-top bg-no-repeat"
          style={{ backgroundImage: "url('/images/operators/the-operators-hero.jpg')" }}
          aria-hidden
        />
        <div
          className="absolute inset-0"
          style={{
            backgroundImage:
              'linear-gradient(to bottom, rgba(20,18,18,0.35) 0%, rgba(20,18,18,0.45) 40%, rgba(20,18,18,0.82) 75%, rgba(20,18,18,0.97) 100%)',
          }}
          aria-hidden
        />
        <div className={`relative z-[2] w-full ${sectionInner} pb-20 pt-[120px]`}>
          <p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-white/40">
            Invitation-Only · Live Leadership Gathering
          </p>
          <h1 className="mb-6 max-w-[860px] font-playfair text-[clamp(40px,5.5vw,72px)] font-normal leading-[1.05] text-white">
            Leadership has no shortage of information. What it lacks is the right room.
          </h1>
          <p className="mb-10 max-w-[600px] text-lg leading-[1.75] text-white/65">
            A live, in-person gathering for people who carry real responsibility and want a place where the
            conversation is worth the drive.
          </p>
          <div className="flex flex-wrap items-center gap-4">
            <button
              type="button"
              onClick={scrollToApply}
              className="inline-block cursor-pointer rounded-[2px] bg-[var(--color-red)] px-8 py-[14px] text-[13px] font-semibold uppercase tracking-[0.06em] text-white transition-opacity hover:opacity-90"
            >
              Request Access
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/operators/login')}
              className="inline-block cursor-pointer rounded-[2px] border border-white/30 bg-transparent px-8 py-[13px] text-[13px] font-semibold uppercase tracking-[0.06em] text-white/80 transition-all hover:border-white/70 hover:text-white"
            >
              Log In
            </button>
          </div>
        </div>
      </section>

      {/* WHAT IT IS */}
      <section className="bg-[var(--color-off-white)]">
        <div className={`${sectionInner} py-[100px]`}>
          <div className="grid grid-cols-1 items-start gap-[80px] lg:grid-cols-2">
            <div>
              <p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--color-brown)]">
                What The Operators Is
              </p>
              <h2 className="mb-7 font-playfair text-[clamp(28px,3vw,42px)] font-normal leading-[1.2] text-[#1A1A1A]">
                A room where leaders invest in each other. Not a network. Not a seminar.
              </h2>
              <p className="mb-5 text-[15px] leading-[1.85] text-[#3A3A3A]">
                The Operators is a live, in-person leadership gathering held at least once per month. A small group
                sits around a table. There is no stage. No presentation. No spectators.
              </p>
              <p className="mb-5 text-[15px] leading-[1.85] text-[#3A3A3A]">
                Topics reflect what leaders are actually building, navigating, and deciding in real time. Growth
                decisions. Organizational complexity. People leadership. Operational pressure. Strategic bets. What
                they share is relevance to the people in the room.
              </p>
              <p className="text-[15px] leading-[1.85] text-[#3A3A3A]">
                The Operators is not about proving competence. It is about what happens when capable leaders choose
                to invest in one another — through attention, engagement, and honest contribution.
              </p>
            </div>
            <div className="flex flex-col gap-[2px]">
              <div className="bg-[var(--color-white)] p-10">
                <span className="mb-5 block text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--color-brown)]">
                  The Operators Is
                </span>
                <ul className="flex flex-col gap-3">
                  {IS_LINES.map((line) => (
                    <li
                      key={line}
                      className="relative pl-4 text-[14px] leading-relaxed text-[#6B6B6B] before:absolute before:left-0 before:top-[11px] before:h-px before:w-[5px] before:bg-[var(--color-red)]"
                    >
                      {line}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-[var(--color-cream)] p-10">
                <span className="mb-5 block text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--color-brown)]">
                  The Operators Is Not
                </span>
                <ul className="flex flex-col gap-3">
                  {ISNT_LINES.map((line) => (
                    <li
                      key={line}
                      className="relative pl-4 text-[14px] leading-relaxed text-[#6B6B6B] before:absolute before:left-0 before:top-[11px] before:h-px before:w-[5px] before:bg-[var(--color-red)]"
                    >
                      {line}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* MECHANICS */}
      <section className="bg-[var(--color-dark)]">
        <div className={`${sectionInner} py-[100px]`}>
          <div className="mb-[60px] max-w-[680px]">
            <p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-white/40">The Structure</p>
            <h2 className="mb-4 font-playfair text-[clamp(28px,3vw,42px)] font-normal leading-[1.2] text-white">
              The mechanics that keep the room honest event after event.
            </h2>
            <p className="text-[15px] leading-[1.75] text-white/55">
              The structure is not arbitrary. Every element exists to protect the quality of the conversation and ensure
              that participation is real — not performed.
            </p>
          </div>
          <div className="grid grid-cols-1 gap-[2px] md:grid-cols-2">
            <div className="border border-white/[0.07] bg-white/[0.04] p-10">
              <h3 className="mb-4 font-playfair text-[22px] font-normal text-white">The Stake</h3>
              <p className="text-[14px] leading-[1.8] text-white/55">
                Every attendee places the stake — in cash — on the table at check-in. It is not a fee. It is a visible
                investment in the room. If you RSVP and don&apos;t show, the stake is still owed. If you leave early,
                you lose eligibility for the ROi. The stake makes commitment tangible before a word is spoken.
              </p>
            </div>
            <div className="border border-white/[0.07] bg-white/[0.04] p-10">
              <h3 className="mb-4 font-playfair text-[22px] font-normal text-white">The Conversation</h3>
              <p className="text-[14px] leading-[1.8] text-white/55">
                Before each event, the system generates scenarios using the bios and current challenges of the people
                attending. These are starting points — not a script. The room determines which threads are pursued and
                how far they go. The conversation is always relevant because it is built from who is actually in the
                room.
              </p>
            </div>
            <div className="border border-white/[0.07] bg-white/[0.04] p-10">
              <h3 className="mb-4 font-playfair text-[22px] font-normal text-white">The Voting</h3>
              <p className="text-[14px] leading-[1.8] text-white/55">
                Operators vote throughout the evening — not for popularity, but to recognize investment. Clarity
                offered. Insight shared. A question that moved the room forward. Support given to someone working through
                something hard. Every Operator has a fixed vote budget and must use all of it for their attendance to
                count.
              </p>
            </div>
            <div className="border border-white/[0.07] bg-white/[0.04] p-10">
              <h3 className="mb-4 font-playfair text-[22px] font-normal text-white">The ROi</h3>
              <p className="text-[14px] leading-[1.8] text-white/55">
                At the end of the night, the ROi — Return on Investment — is awarded to the person whose contribution most
                meaningfully supported others in the discussion. The pot is transparent. The distribution is clear. The
                system rewards quality engagement, not performance. You cannot win by talking the most.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ROLES */}
      <section className="bg-[var(--color-white)]">
        <div className={`${sectionInner} py-[100px]`}>
          <div className="mb-[60px] max-w-[680px]">
            <p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--color-brown)]">
              Roles in the Room
            </p>
            <h2 className="mb-4 font-playfair text-[clamp(28px,3vw,42px)] font-normal leading-[1.2] text-[#1A1A1A]">
              Three roles. Clear responsibilities. No ambiguity about what you are there to do.
            </h2>
            <p className="text-[15px] leading-[1.75] text-[#6B6B6B]">
              Every person in the room has a defined role. The structure is what allows the conversation to go deep
              without drifting.
            </p>
          </div>
          <div className="grid grid-cols-1 gap-[2px] md:grid-cols-3">
            <div className="bg-[var(--color-cream)] p-10">
              <span className="mb-5 block text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--color-brown)]">
                The Authority
              </span>
              <h3 className="mb-4 font-playfair text-[22px] font-normal text-[#1A1A1A]">Chief Operator</h3>
              <p className="mb-3 text-[14px] leading-[1.8] text-[#6B6B6B]">
                Responsible for the integrity of the event. Creates and manages events, approves Candidates, ensures the
                structure is followed.
              </p>
              <p className="text-[14px] leading-[1.8] text-[#6B6B6B]">
                Participates fully in discussion and contributes as any Operator would. Does not compete for the ROi. The
                Chief Operator is the authority in the room.
              </p>
            </div>
            <div className="bg-[var(--color-off-white)] p-10">
              <span className="mb-5 block text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--color-brown)]">
                Full Membership
              </span>
              <h3 className="mb-4 font-playfair text-[22px] font-normal text-[#1A1A1A]">Operator</h3>
              <p className="mb-3 text-[14px] leading-[1.8] text-[#6B6B6B]">
                Full participant. RSVPs and attends events. Engages fully in discussion. Casts votes throughout the
                evening. Eligible to receive the ROi.
              </p>
              <p className="text-[14px] leading-[1.8] text-[#6B6B6B]">
                Operators may invite Candidates to events, subject to Chief Operator approval. Operator status is earned
                through the community, not granted at the door.
              </p>
            </div>
            <div className="bg-[var(--color-off-white)] p-10">
              <span className="mb-5 block text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--color-brown)]">
                The Path In
              </span>
              <h3 className="mb-4 font-playfair text-[22px] font-normal text-[#1A1A1A]">Candidate</h3>
              <p className="mb-3 text-[14px] leading-[1.8] text-[#6B6B6B]">
                Invited participants on the path to full membership. May attend events once approved. May participate
                fully in discussion.
              </p>
              <p className="text-[14px] leading-[1.8] text-[#6B6B6B]">
                At the close of each event, a simple majority vote determines whether a Candidate is promoted to
                Operator. There is no guarantee. That is the point.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* WHO */}
      <section className="bg-[var(--color-cream)]">
        <div className={`${sectionInner} py-[100px]`}>
          <div className="grid grid-cols-1 items-start gap-[100px] lg:grid-cols-[300px_1fr]">
            <div className="lg:sticky lg:top-24">
              <p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--color-brown)]">
                Who This Is For
              </p>
              <h2 className="mb-4 font-playfair text-[clamp(24px,2.5vw,36px)] font-normal leading-[1.2] text-[#1A1A1A]">
                This room is not for everyone.
              </h2>
              <p className="text-[14px] leading-[1.75] text-[#6B6B6B]">
                It is for people who value real conversation, respect structure, and are willing to invest in others
                without knowing the outcome in advance.
              </p>
            </div>
            <div>
              <p className="mb-6 text-[15px] leading-[1.85] text-[#3A3A3A]">
                If you show up to prove how capable you are, this room will not reward you. If you show up to help
                others think more clearly, it will.
              </p>
              <p className="mb-6 text-[15px] leading-[1.85] text-[#3A3A3A]">
                The Operators is for founders, executives, and business leaders who are actively building —
                organizations with real people, real decisions, and real consequences. People who have been in rooms
                that felt safe and left wondering why nothing changed.
              </p>
              <div className="my-8 border-l-2 border-[var(--color-red)] pl-6">
                <p className="font-playfair text-[19px] italic leading-relaxed text-[#1A1A1A]">
                  The real cost is posture. Laying down ego, image, and defensiveness is not easy. Neither is listening
                  carefully or investing in others when you carry as much as most leaders in this room carry.
                </p>
              </div>
              <p className="mb-6 text-[15px] leading-[1.85] text-[#3A3A3A]">
                Company size does not define who belongs here. What you carry does. If you lead people and make
                decisions that affect their lives, and you want a room that treats that weight seriously — this is
                worth your time to find out.
              </p>
              <p className="text-[15px] leading-[1.85] text-[#3A3A3A]">
                If you are looking for leads, looking to pitch, or looking to be seen — this is not that room.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* APPLY */}
      <section id="apply" className="bg-[var(--color-dark)] scroll-mt-6">
        <div className={`${sectionInner} py-[100px]`}>
          <div className="grid grid-cols-1 items-start gap-[80px] lg:grid-cols-[380px_1fr]">
            <div>
              <p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-white/40">Request Access</p>
              <h2 className="mb-6 font-playfair text-[clamp(28px,3vw,42px)] font-normal leading-[1.2] text-white">
                100% reviewed. No automatic acceptance. Yours to tell.
              </h2>
              <p className="mb-5 text-[15px] leading-[1.85] text-white/60">
                Membership is invitation-only. This form puts you in the review queue. A Chief Operator will read your
                submission and reach out if The Operators is the right fit.
              </p>
              <p className="mb-5 text-[15px] leading-[1.85] text-white/60">
                There is no guarantee of acceptance.{' '}
                <strong className="font-medium text-white/90">Write your bio as if we have never heard of you — because we haven&apos;t.</strong>
              </p>
              <p className="text-[15px] leading-[1.85] text-white/60">No automated responses. No timeline promises. Real people. Real review.</p>
            </div>
            <div>
              {!success ? (
                <form
                  onSubmit={handleSubmit}
                  className="border border-white/[0.08] bg-white/[0.04] p-12"
                  noValidate
                >
                  <div className="mb-4 grid grid-cols-1 gap-4 md:grid-cols-2">
                    <div className="flex flex-col gap-2">
                      <label className="text-[12px] font-semibold uppercase tracking-[0.06em] text-white/55">
                        Full Name <span className="ml-0.5 text-[var(--color-red)]">*</span>
                      </label>
                      <input
                        type="text"
                        required
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        className="w-full rounded-[2px] border border-white/12 bg-white/[0.06] px-4 py-3 font-inter text-sm text-white outline-none transition-colors placeholder:text-white/25 focus:border-white/40"
                        placeholder="Your full name"
                        autoComplete="name"
                      />
                    </div>
                    <div className="flex flex-col gap-2">
                      <label className="text-[12px] font-semibold uppercase tracking-[0.06em] text-white/55">
                        Email Address <span className="ml-0.5 text-[var(--color-red)]">*</span>
                      </label>
                      <input
                        type="email"
                        required
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        className="w-full rounded-[2px] border border-white/12 bg-white/[0.06] px-4 py-3 font-inter text-sm text-white outline-none transition-colors placeholder:text-white/25 focus:border-white/40"
                        placeholder="you@yourcompany.com"
                        autoComplete="email"
                      />
                    </div>
                  </div>
                  <div className="mb-4 grid grid-cols-1 gap-4 md:grid-cols-2">
                    <div className="flex flex-col gap-2">
                      <label className="text-[12px] font-semibold uppercase tracking-[0.06em] text-white/55">
                        Role or Title <span className="ml-0.5 text-[var(--color-red)]">*</span>
                      </label>
                      <input
                        type="text"
                        required
                        value={roleTitle}
                        onChange={(e) => setRoleTitle(e.target.value)}
                        className="w-full rounded-[2px] border border-white/12 bg-white/[0.06] px-4 py-3 font-inter text-sm text-white outline-none transition-colors placeholder:text-white/25 focus:border-white/40"
                        placeholder="CEO, Founder, COO..."
                        autoComplete="organization-title"
                      />
                    </div>
                    <div className="flex flex-col gap-2">
                      <label className="text-[12px] font-semibold uppercase tracking-[0.06em] text-white/55">
                        Company Size <span className="ml-0.5 text-[var(--color-red)]">*</span>
                      </label>
                      <select
                        required
                        value={companySize}
                        onChange={(e) => setCompanySize(e.target.value)}
                        className="w-full rounded-[2px] border border-white/12 bg-white/[0.06] px-4 py-3 font-inter text-sm text-white outline-none transition-colors focus:border-white/40 [&>option]:bg-[var(--color-dark)]"
                      >
                        {COMPANY_OPTIONS.map((opt) => (
                          <option key={opt.value || 'placeholder'} value={opt.value} disabled={opt.disabled}>
                            {opt.label}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>
                  <div className="mb-4 flex flex-col gap-2">
                    <label className="text-[12px] font-semibold uppercase tracking-[0.06em] text-white/55">
                      Your Bio <span className="ml-0.5 text-[var(--color-red)]">*</span> — Who are you, what do you
                      lead, and what does your leadership actually look like day to day?
                    </label>
                    <textarea
                      required
                      value={bio}
                      onChange={(e) => setBio(e.target.value)}
                      minLength={100}
                      className="min-h-[220px] w-full resize-y rounded-[2px] border border-white/12 bg-white/[0.06] p-4 font-inter text-sm text-white outline-none transition-colors placeholder:text-white/25 focus:border-white/40"
                      placeholder="Write as if we have never heard of you. What you lead, how you lead it, what you carry."
                    />
                    <p className="text-right text-[12px] text-white/30">{counterText}</p>
                  </div>
                  <div className="my-7 h-px bg-white/[0.08]" />
                  <p className="mb-6 text-[13px] italic leading-[1.65] text-white/40">
                    Your information is not shared publicly. You will not be added to any mailing list. This goes
                    directly to the Chief Operator for review.
                  </p>
                  {errorMessage ? (
                    <p className="mb-4 text-sm text-red-300" role="alert">
                      {errorMessage}
                    </p>
                  ) : null}
                  <div className="flex flex-wrap items-center justify-between gap-5">
                    <button
                      type="submit"
                      disabled={submitting}
                      className="inline-block cursor-pointer rounded-[2px] bg-[var(--color-red)] px-8 py-[14px] text-[13px] font-semibold uppercase tracking-[0.06em] text-white transition-opacity disabled:opacity-60"
                    >
                      {submitting ? 'Sending…' : 'Submit Application'}
                    </button>
                    <p className="max-w-[300px] text-[12px] leading-snug text-white/30">
                      No timeline. No automated follow-up. If it&apos;s the right room, you will hear from us.
                    </p>
                  </div>
                </form>
              ) : (
                <div className="border border-white/[0.12] bg-white/[0.04] px-10 py-[60px] text-center">
                  <h3 className="mb-4 font-playfair text-[32px] font-normal text-white">Received.</h3>
                  <p className="text-[15px] leading-[1.75] text-white/60">
                    Your application is in the queue. If The Operators is the right room for where you are, you will
                    hear from us.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* CLOSE */}
      <section className="border-t border-white/[0.06] bg-[var(--color-dark)] px-6 py-[100px] text-center sm:px-10">
        <div className="mx-auto max-w-[760px]">
          <p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-white/40">If You&apos;re Ready</p>
          <h2 className="mb-5 font-playfair text-[clamp(28px,3.5vw,48px)] font-normal leading-[1.15] text-white">
            The room exists. The question is whether you belong in it.
          </h2>
          <p className="mb-10 text-base leading-[1.85] text-white/55">One gathering. Real leaders. No performance.</p>
          <div className="flex flex-wrap justify-center gap-4">
            <button
              type="button"
              onClick={scrollToApply}
              className="inline-block cursor-pointer rounded-[2px] bg-[var(--color-red)] px-8 py-[14px] text-[13px] font-semibold uppercase tracking-[0.06em] text-white transition-opacity hover:opacity-90"
            >
              Request Access
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/operators/login')}
              className="inline-block cursor-pointer rounded-[2px] border border-white/30 bg-transparent px-8 py-[13px] text-[13px] font-semibold uppercase tracking-[0.06em] text-white/80 transition-all hover:border-white/70 hover:text-white"
            >
              Already a Member? Log In
            </button>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-white/[0.06] bg-[#1A1818]">
        <div className={`${sectionInner} grid grid-cols-2 gap-10 py-[60px] md:grid-cols-4`}>
          <div>
            <h4 className="mb-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--color-brown)]">About</h4>
            <button
              type="button"
              onClick={() => handleNavigate('/meet-bart')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              About Bart
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/books')}
              className="block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Books
            </button>
          </div>
          <div>
            <h4 className="mb-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--color-brown)]">
              Methods
            </h4>
            <button
              type="button"
              onClick={() => handleNavigate('/advisory')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Leadership Advisory
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/consulting')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Consulting
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/fractional-roles')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Fractional Roles
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/the-room')}
              className="block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              The Room (book)
            </button>
          </div>
          <div>
            <h4 className="mb-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--color-brown)]">
              Culture Science
            </h4>
            <button
              type="button"
              onClick={() => handleNavigate('/culture-science')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Culture Science
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/culture-science/ali')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              ALI
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/culture-science/anti-projects/scoreboard-leadership')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Scoreboard Leadership
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/culture-science/anti-projects/bad-leader-project')}
              className="block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Bad Leader Project
            </button>
          </div>
          <div>
            <h4 className="mb-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--color-brown)]">
              Connect
            </h4>
            <button
              type="button"
              onClick={() => handleNavigate('/contact')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Contact
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/journal')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Journal
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/archy')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Meet Archy
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/engagement-inquiry')}
              className="mb-2 block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              Work Together
            </button>
            <button
              type="button"
              onClick={() => handleNavigate('/operators')}
              className="block w-full text-left text-[13px] text-white/40 transition-colors hover:text-white/80"
            >
              The Operators
            </button>
          </div>
        </div>
        <div className={`${sectionInner} border-t border-white/[0.06] py-6 text-[12px] text-white/25`}>
          © {new Date().getFullYear()} Archetype Original. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
