
name: Build Knowledge Index

on:
  push:
    paths:
      - "knowledge/**"
      - "scripts/**"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i gray-matter@^4.0.3
      - run: node scripts/build-index.mjs
      - name: Commit knowledge.json
        run: |
          git config user.name "AO Build Bot"
          git config user.email "bot@archetypeoriginal.local"
          git add public/knowledge.json
          git commit -m "build: update knowledge index" || echo "No changes"
          git push
